export const LOCATIONS = [
    { id: 0, name: 'All Locations' },
    { id: 9, name: 'Sydney Airport' },
    { id: 19, name: 'Brisbane Airport' },
    { id: 15, name: 'Cairns Airport' },
    { id: 8, name: 'Adelaide Airport' },
    { id: 17, name: 'Melbourne Airport' },
    { id: 22, name: 'Perth Airport' },
];
export const Loc = [
    { code: "SYD", locid: 9 },
    { code: "BNE", locid: 19 },
    { code: "CNS", locid: 15 },
    { code: "ADL", locid: 8 },
    { code: "MEL", locid: 17 },
    { code: "PER", locid: 22 },
];

export const CATEGORIES = [
    { id: 91, name: 'Medium Sedan Hybrid' },
    { id: 101, name: 'Small SUV Hybrid' },
    { id: 102, name: 'Intermediate Elite SUV' },
    { id: 103, name: 'Economy Hybrid' },
    { id: 89, name: 'Family SUV 5 Seater' },
    { id: 29, name: 'Mini' },
    { id: 30, name: 'Hatchback' },
    { id: 48, name: 'Economy' },
    { id: 87, name: 'Intermediate SUV' },
    { id: 31, name: 'Medium Sedan' },
    { id: 32, name: 'Large Sedan' },
    { id: 66, name: 'Hatchback Hybrid' },
    { id: 39, name: 'Compact SUV' },
    { id: 69, name: 'Crossover SUV' },
    { id: 33, name: 'Medium SUV' },
    { id: 60, name: 'Small SUV' },
    { id: 81, name: 'Premium SUV 7 Seater' },
    { id: 82, name: 'Luxury SUV 7 Seater' },
    { id: 73, name: 'Economy SUV' },
    { id: 64, name: 'Mid SUV Hybrid' },
    { id: 34, name: 'Family SUV 7 Seater' },
    { id: 67, name: 'Large Sedan Hybrid' },
    { id: 35, name: 'People Mover 8 Seater' },
    { id: 88, name: 'Commuter Bus 11 Seater' },
    { id: 46, name: 'Commuter Bus 12 Seater' },
    { id: 47, name: 'Delivery Van' },
    { id: 70, name: 'High Top Van' },
    { id: 100, name: 'Premium Dual Cab Ute' },
    { id: 92, name: 'Ute Dual Cab 4x4' },
    { id: 85, name: 'Ute Dual Cab Pick-up' },
];
